name: my_flutter
description: New Flutter application for learning.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  #国际化支持
  flutter_localizations:
    sdk: flutter

  # TO UPDATE USE "flutter update-packages --force-upgrade"
  # UPDATE PACKAGES DATA 2019/11/30
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  # https://github.com/tekartik/synchronized.dart
  synchronized: ^2.1.0+2
  # 本地存储 官方插件 https://github.com/flutter/plugins
  shared_preferences: ^0.5.4+6
  # 路由 https://github.com/theyakka/fluro
  fluro: ^1.5.1
  # Toast库 https://github.com/PonnamKarthik/FlutterToast
  fluttertoast: ^3.1.3
  # 加载网络图片 https://github.com/renefloor/flutter_cached_network_image
  cached_network_image: ^1.1.3
  # 适配Android 和IOS 的App图标
  flutter_launcher_icons: ^0.7.4
  # 权限申请 https://github.com/Baseflow/flutter-permission-handler
  permission_handler: ^4.0.0
  # 日期格式化 https://github.com/dart-lang/intl
  intl: ^0.15.8
  # dio 网络请求 https://github.com/flutterchina/dio
  dio: ^3.0.7
  # 刷新加载 https://github.com/peng8350/flutter_pulltorefresh
  pull_to_refresh: ^1.5.7
  # 文件路径 官方插件 https://github.com/flutter/plugins
  path_provider: ^1.4.5
  # google 图表 https://google.github.io/charts/flutter/gallery.html
  charts_flutter: ^0.8.1
  # 检测网络状态 https://github.com/flutter/plugins/tree/master/packages/connectivity
  connectivity: ^0.4.5+6
  # webview 官方插件 https://github.com/flutter/plugins
  # webview_flutter: ^0.3.15+1
  webview_flutter:
    path: webview_flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

# 适配 Android 和 IOS 的图标
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/images/
    - assets/product/

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
